name: Build

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run:
          make build